import { anthropic } from "@ai-sdk/anthropic"
import { FILE_UPLOAD_FEATURE, PDF_PROCESSING_FEATURE, REASONING_FEATURE, REASONING_FEATURE_DISABLED } from "../features"

export const ANTHROPIC_MODELS = [
  {
    id: "claude-3-5-sonnet-20241022",
    name: "Claude 3.5 Sonnet",
    provider: "anthropic",
    premium: true,
    usesPremiumCredits: true,
    description: `Powerful language model from Anthropic.\\nExcels at creative writing and summaries.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: anthropic("claude-3-5-sonnet-20241022"),
  },
  {
    id: "claude-3-7-sonnet-20250219",
    name: "Claude 3.7 Sonnet",
    provider: "anthropic",
    premium: true,
    usesPremiumCredits: true,
    description: `Latest generation model with improved context handling.\\nProvides reliable results across domains.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: anthropic("claude-3-7-sonnet-20250219"),
  },
  {
    id: "claude-3-7-sonnet-reasoning",
    name: "Claude 3.7 Sonnet (Reasoning)",
    provider: "anthropic",
    premium: true,
    usesPremiumCredits: true,
    description: `Reasoning-optimized variant of Claude 3.7.\\nDesigned for analytical tasks and tool use.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
    ],
    api_sdk: anthropic("claude-3-7-sonnet-20250219"),
  },
  {
    id: "claude-4-opus",
    name: "Claude 4 Opus",
    provider: "anthropic",
    premium: false,
    usesPremiumCredits: false,
    description: `Entry point to the Claude 4 family.\\nOffers solid performance at a lower cost.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
    ],
    api_sdk: anthropic("claude-opus-4-20250514"),
  },
  {
    id: "claude-4-sonnet",
    name: "Claude 4 Sonnet",
    provider: "anthropic",
    premium: true,
    usesPremiumCredits: true,
    description: `Middle tier of the Claude 4 lineup.\\nProvides strong performance for most tasks.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: anthropic("claude-sonnet-4-20250514"),
  },
  {
    id: "claude-4-sonnet-reasoning",
    name: "Claude 4 Sonnet (Reasoning)",
    provider: "anthropic",
    premium: true,
    usesPremiumCredits: true,
    description: `Enhanced Sonnet model with dedicated reasoning mode.\\nBest for tool use and problem solving.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
    ],
    api_sdk: anthropic("claude-sonnet-4-20250514"),
  },
]