import { google } from "@ai-sdk/google"
import { fal } from "@ai-sdk/fal"
import { FILE_UPLOAD_FEATURE, PDF_PROCESSING_FEATURE, REASONING_FEATURE, REASONING_FEATURE_DISABLED, REASONING_FEATURE_BASIC, WEB_SEARCH_FEATURE, IMAGE_GENERATION_FEATURE } from "../features"

export const GOOGLE_MODELS = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Baseline Gemini model with fast inference.\\nGreat for general tasks and web search.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.0-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Baseline Gemini model with fast inference.\\nGreat for general tasks and web search.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.0-flash-lite"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Enhanced Gemini model with reasoning capabilities.\\nIdeal for complex problem-solving and analysis.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-thinking",
    name: "Gemini 2.5 Flash (Thinking)",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    description: `Enhanced Gemini model with reasoning capabilities.\\nIdeal for complex problem-solving and analysis.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-lite-preview-06-17",
    name: "Gemini 2.5 Flash Lite",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Enhanced Gemini model with reasoning capabilities.\\nIdeal for complex problem-solving and analysis.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash-lite-preview-06-17"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-lite-preview-06-17-thinking",
    name: "Gemini 2.5 Flash Lite (Thinking)",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    description: `Enhanced Gemini model with reasoning capabilities.\\nIdeal for complex problem-solving and analysis.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash-lite-preview-06-17"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description: `Premium Gemini model with enhanced reasoning.\\nIdeal when you need the best quality responses.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      WEB_SEARCH_FEATURE,
    ],
    api_sdk: google("gemini-2.5-pro"),
  },  
  {
    id: "imagen-4",
    name: "Imagen 4",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description: `Google's flagship text-to-image model.\\nOffers significantly improved text rendering and photorealistic images.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      IMAGE_GENERATION_FEATURE,
    ],
    api_sdk: fal.image("fal-ai/imagen4/preview/fast"),  
  },
  {
    id: "imagen-4-ultra",
    name: "Imagen 4 Ultra",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description: `Google's premium image model for precise instruction following.\\nDesigned for when you need images that precisely follow prompts.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      IMAGE_GENERATION_FEATURE,
    ],
    api_sdk: fal.image("fal-ai/imagen4/preview/ultra"),
  },
]