import { google } from "@ai-sdk/google"
import { fal } from "@ai-sdk/fal"
import { FILE_UPLOAD_FEATURE, PDF_PROCESSING_FEATURE, REASONING_FEATURE, REASONING_FEATURE_DISABLED, WEB_SEARCH_FEATURE, IMAGE_GENERATION_FEATURE } from "../features"

export const GOOGLE_MODELS = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Google's fast multimodal model with native tool use.\\nExcels at general tasks, web search, and real-time applications.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.0-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Most cost-efficient Gemini model with fast responses.\\nIdeal for high-volume, latency-sensitive applications.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.0-flash-lite"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Google's flagship light model.\\nExcels at agentic use cases and large-scale processing.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-thinking",
    name: "Gemini 2.5 Flash (Thinking)",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    description: `Gemini flagship light model with reasoning capabilities enabled.\\nFeatures visible thought process for complex problem-solving with thinking.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-lite-preview-06-17",
    name: "Gemini 2.5 Flash Lite",
    provider: "gemini",
    premium: false,
    usesPremiumCredits: false,
    description: `Most cost-efficient and fastest model with lowest latency.\\nIdeal for high-volume classification and summarization tasks.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash-lite-preview-06-17"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-lite-preview-06-17-thinking",
    name: "Gemini 2.5 Flash Lite (Thinking)",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    description: `Flash Lite with adjustable thinking budget for reasoning.\\nCombines cost-efficiency with controllable thinking capabilities.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash-lite-preview-06-17"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      WEB_SEARCH_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description: `Google's state-of-the-art model leading math and science benchmarks.\\nExcels at creating web apps and agentic code applications.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      WEB_SEARCH_FEATURE,
    ],
    api_sdk: google("gemini-2.5-pro"),
  },  
  {
    id: "imagen-4",
    name: "Imagen 4",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description: `Google's flagship text-to-image model with superior text rendering.\\nCreates photorealistic images with precise instruction following.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      IMAGE_GENERATION_FEATURE,
    ],
    api_sdk: fal.image("fal-ai/imagen4/preview/fast"),  
  },
  {
    id: "imagen-4-ultra",
    name: "Imagen 4 Ultra",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description: `Ultra-precise image generation model with enhanced prompt adherence.\\nDesigned for professional applications requiring exact specifications.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      IMAGE_GENERATION_FEATURE,
    ],
    api_sdk: fal.image("fal-ai/imagen4/preview/ultra"),
  },
]