import { openai } from "@ai-sdk/openai"
import { FILE_UPLOAD_FEATURE, PDF_PROCESSING_FEATURE, REASONING_FEATURE, REASONING_FEATURE_DISABLED, IMAGE_GENERATION_FEATURE } from "../features"

export const OPENAI_MODELS = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    premium: true,
    usesPremiumCredits: false,
    description: `Flagship model with balanced performance.\\nGreat for everyday conversations.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: openai("gpt-4o"),
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `Lightweight variant offering fast responses.\\nIdeal for quick questions and mobile use.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: openai("gpt-4o-mini"),
  },
  {
    id: "o4-mini",
    name: "o4 Mini",
    provider: "openai",
    premium: true,
    usesPremiumCredits: false,
    description: `Compact model optimized for reasoning tasks.\\nProvides good accuracy with lower costs.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
    ],
    api_sdk: openai("o4-mini"),
  },
  {
    id: "o3",
    name: "o3",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    description: `Advanced model for more complex reasoning.\\nBest suited for in-depth conversations.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
    ],
    api_sdk: openai("o3"),
  },
  {
    id: "o3-pro",
    name: "o3 Pro",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `Enhanced version with additional capabilities.\\nIdeal for professional use.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
    ],
    api_sdk: openai("o3-pro"),
  },
  {
    id: "gpt-image-1",
    name: "GPT Image 1",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    description: `AI model specialized for generating high-quality images.\\nPerfect for creating visual content from text descriptions.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      IMAGE_GENERATION_FEATURE,
    ],
    api_sdk: openai.image("gpt-image-1"),
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    premium: true,
    usesPremiumCredits: false,
    description: `Updated architecture with improved efficiency.\\nProvides consistent results for complex prompts.`,
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: openai("gpt-4.1"),
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `Scaled-down model for quick chats.\\nBalances speed and quality for everyday use.`,
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: openai("gpt-4.1-mini"),
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `Ultra-light model for minimal latency.\\nGreat when resources are limited.`,
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: openai("gpt-4.1-nano"),
  },
  {
    id: "gpt-4.5",
    name: "GPT-4.5",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `Stepping stone between major versions.\\nOffers incremental improvements over 4.1.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
    ],
    api_sdk: openai("gpt-4.5"),
  },
]