import { gateway } from '@ai-sdk/gateway';
import { openai } from '@ai-sdk/openai';
import {
  FILE_UPLOAD_FEATURE,
  IMAGE_GENERATION_FEATURE,
  PDF_PROCESSING_FEATURE,
  REASONING_FEATURE,
  REASONING_FEATURE_DISABLED,
  TOOL_CALLING_FEATURE,
} from '../features';
// import { openrouter } from '../openrouter';

export const OPENAI_MODELS = [
  {
    id: 'gpt-oss-20b',
    name: 'GPT OSS 20B',
    provider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description: `OpenAI's new smaller 20B open-source model. \nAround o3-mini performance, with super fast inference by Groq.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [REASONING_FEATURE, TOOL_CALLING_FEATURE],
    api_sdk: gateway('openai/gpt-oss-20b'),
  },
  {
    id: 'gpt-oss-120b',
    name: 'GPT OSS 120B',
    provider: 'openai',
    displayProvider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description: `OpenAI's new larger 120B open-source model. \nNearly as good as o4-mini, with super fast inference by Groq.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [REASONING_FEATURE, TOOL_CALLING_FEATURE],
    api_sdk: gateway('openai/gpt-oss-120b'),
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    premium: true,
    usesPremiumCredits: false,
    description: `OpenAI's flagship multimodal model.\nProcesses text, images, and audio with fast, versatile performance.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('gpt-4o'),
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description:
      'Cost-efficient model with fast inference speed.\nPerfect for high-volume tasks and quick interactions.',
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('gpt-4o-mini'),
  },
  {
    id: 'o4-mini',
    name: 'o4 Mini',
    provider: 'openai',
    premium: true,
    usesPremiumCredits: false,
    description:
      'Reasoning-focused model with 93% on AIME 2025.\nExcels at math, coding, and visual tasks at lower cost.',
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('o4-mini'),
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'openai',
    premium: true,
    usesPremiumCredits: true,
    description:
      'Advanced reasoning model with 20% fewer errors than o1.\nExcels at programming, consulting, and creative tasks.',
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('o3'),
  },
  {
    id: 'o3-pro',
    name: 'o3 Pro',
    provider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description:
      'Premium reasoning model with enhanced capabilities.\nDesigned for research-level and professional applications.',
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('o3-pro'),
  },
  {
    id: 'gpt-image-1',
    name: 'GPT Image 1',
    provider: 'openai',
    premium: true,
    usesPremiumCredits: true,
    description:
      'Specialized image generation model from OpenAI.\nCreates high-quality visuals from detailed text prompts.',
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: openai.image('gpt-image-1'),
  },
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    premium: true,
    usesPremiumCredits: false,
    description:
      'Enhanced GPT-4 with 55% on SWE-bench Verified.\nDelivers major improvements in coding and instruction following.',
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('gpt-4.1'),
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description:
      'Efficient model balancing speed and capability.\nIdeal for everyday conversations and quick tasks.',
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('gpt-4.1-mini'),
  },
  {
    id: 'gpt-4.1-nano',
    name: 'GPT-4.1 Nano',
    provider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description:
      'Ultra-lightweight model with minimal latency.\nOptimized for resource-constrained environments.',
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('gpt-4.1-nano'),
  },
  {
    id: 'gpt-4.5',
    name: 'GPT-4.5',
    provider: 'openai',
    premium: false,
    usesPremiumCredits: false,
    description:
      'General-purpose model with enhanced understanding.\nOffers better nuance, creativity, and aesthetic intuition.',
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai('gpt-4.5'),
  },
];
